addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - $HOME/.npm
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - 8
  - 7
  - 6
  - 5
  - "0.12"
  - "0.10"
script: "./coverage.sh"
sudo: false
